on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest  # Use Ubuntu as it has better support for Docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./.github/workflows
          file: ./.github/workflows/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
