# Sert à relancer le workflow à chaque fois que le projet est push
on:
  push:
    branches:
      - 'main'
# initie ubuntu, dans sa dernière version pour faire tourner le workflow.
jobs:
  docker:
    runs-on: ubuntu-latest  # Use Ubuntu as it has better support for Docker
# check out la repo, je sais toujours pas à quoi ça sert
    steps:
      - name: Checkout
        uses: actions/checkout@v4
# initie le Buildx de Docker, pour du cross platform
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
# se connecte au container registry de GitHub, j'ai pas encore bien saisi ce que c'est,
# Notez bien le CR_PAT, on y rvient après
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
# A chaque fois qu'on push sur notre repo,
# Docker ira chercher les Dockerfiles dans le dossier indiqué
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./.github/workflows
          file: ./.github/workflows/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
